### ISSUE TITLE
ground truth segmentation of extra_sunrgbd data is not right

### ISSUE THREAD

**Issue by caixiaohai666** [qq456cvb/CPPF#1]
Hi, thanks for sharing the codes of the excellent work. 
I run the code `sunrgbd/inference.py`, and I save the original back-projected points and the segmented points.
For the `bed` instance, the yellow point is the original back-projected points (from `bed_pc.npz`), and the blue points (chosen by using `bed_segment.pkl`). It seems that the blue points loss some part when indexing the original back-projected points by `bed_segment.pkl`.
So is there something wrong with the `bed_segment.pkl`?
<img width="473" alt="截屏2022-04-29 19 37 49" src="https://user-images.githubusercontent.com/102866212/165937374-f6a9ecc4-5dc0-4688-99f6-192fc8b4ac29.png">

**Comment by qq456cvb** [comment]
Hi, thanks for your interest in our work. We generate the 3D segments using the provided 2D instance masks provided by SUNRGB-D dataset. From the figure you provided, it seems that the original 2D instance mask does not include the blanket/comforter on the bed. It is hard to tell a comforter or blanket from point clouds only, and you may confirm this by viewing the corresponding RGB image.

**Comment by qq456cvb** [comment]
Moreover, it is definitely helpful to include the comforter into the mask, from the point clouds' perspective, since it provides the basic geometry of the bed. This may also explain why our method is good at bathtub, but not so good at bed.

**Comment by caixiaohai666** [comment]
Thanks for you prompt reply.  I will check the corresponding RGB image.
