### ISSUE TITLE
Results on 10 degrees, 10 cm metric on NOCS dataset

### ISSUE THREAD

**Issue by AlbertoRemus** [qq456cvb/CPPF#2]
![Screenshot from 2022-09-21 17-36-47](https://user-images.githubusercontent.com/54797872/191548468-90edef79-a5fd-4697-b759-f273c18a45b7.png)

Hello, thanks for your interesting work!

I would like to ask if you have a numerical result on the 10 degrees, 10 cm metric on NOCS dataset

I thank you in advance

Alberto

**Comment by qq456cvb** [comment]
Actually, the difficulty part is the rotation estimation instead of translation, and around 90% of translation is within 5cm as I could remember. 10deg 10cm is 46.0, slightly higher than 10deg 5cm.

**Comment by AlbertoRemus** [comment]
@qq456cvb, many thanks for your reply!
