### ISSUE TITLE
关于实验

### ISSUE THREAD

**Issue by touchthefish233** [qq456cvb/CPPF#3]
请问，我按照工程中的步骤没有复现出文章中的结果，结果如下 ： 
![image](https://user-images.githubusercontent.com/68363637/234199161-02aae2e8-8dfd-4d21-ab66-af7afc182ebd.png)
![image](https://user-images.githubusercontent.com/68363637/234199228-34f30a38-fcec-473a-8d66-ad41dbec23ce.png)

**Comment by qq456cvb** [comment]
看log是bowl和laptop出现了异常，正常情况下这两个应该预测得比较准。我们在一开始的版本后更新了一些代码，你可以试着用https://github.com/qq456cvb/CPPF/blob/ab7e882aa86ca2d8e5dbe6de2400781673accf94/models/voting.py 替换现有的voting.py看看结果如何。另外，你可以看下如果直接拿我们预训练的模型测试结果如何，这样能方便我们更好地定位问题。

**Comment by touchthefish233** [comment]
非常感谢受到你的回复，这个结果是加载的提供的预训练模型的结果，并未进行重新训练； 好的，我将替换voting.py进行测试

**Comment by touchthefish233** [comment]
![image](https://user-images.githubusercontent.com/68363637/234296598-8731a4aa-9ac0-4c0f-b0e5-cc4020949184.png)
如果简单的进行替换，会显示如下的错误，请问需要额外配置其他环境吗

**Comment by qq456cvb** [comment]
看样子是编译错误，试试第五行的路径更改成你github目录下的helper_math.cuh的路径https://github.com/qq456cvb/CPPF/blob/ab7e882aa86ca2d8e5dbe6de2400781673accf94/models/voting.py#L5。

**Comment by touchthefish233** [comment]
非常感谢您的解答！
