### ISSUE TITLE
the groundtruth in ShapeNetDataset

### ISSUE THREAD

**Issue by Lirity** [qq456cvb/CPPF#4]
Hello, I have been referring to the ShapeNetDataset section in your code recently, where the translation, rotation and scale seem to be in the form of classification. May I ask which part of the code defines the groundtruth of thetranslation, rotation and scale in matrix form.Thanks!

**Comment by qq456cvb** [comment]
You can refer to https://github.com/qq456cvb/CPPF/blob/main/utils/dataset.py#L232 where we convert a real value into a set of discrete bins for classification. If you look for a matrix form of ground-truth pose, you may refer to https://github.com/qq456cvb/CPPF/blob/main/utils/dataset.py#L181, but be careful this matrix pose is in the coordinate of ShapeNet, which is different from NOCS'.
